@extends('frontends.template-part.master')      
@section('content-homepage')
<div class="theme-inner-banner section-spacing" style="background: url({{asset('assets/frontends/images/Edit/veanoibo03.png)')}} no-repeat center; background-size:cover;">
                        <div class="overlay">
                              <div class="container">
                                    <h2 class="title">Lãnh Đạo Tổng Cục Môi Trường</h2>
                                    <ul>
                                          <li><a href="index.html">Trang Chủ</a></li>
                                          <li>-</li>
                                          <li><a href="#">Giới Thiệu</a></li>
                                          <li>-</li>
                                          <li>Lãnh Đạo Tổng Cục</li>
                                    </ul>
                              </div>
                        </div> <!-- /.overlay -->
                  </div> <!-- /.theme-inner-banner -->
                  
                  


                  <div class="container" style="margin-bottom: 5%">
                        <div class="detail-new-content" style="text-align:justify;color:#000000;font-family:arial, helvetica, sans-serif;background-color:#ffffff;display:flex;justify-content:center;"><span id="ms-rterangecursor-end"></span>
         <div aria-labelledby="ctl00_PlaceHolderTopColMiddle_ctl03_label" style="display:inline;"><div style="text-align:center;"><div style="background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-attachment:initial;background-origin:initial;background-clip:initial;margin:0cm 0cm 0pt;line-height:normal;">&nbsp;</div><table class="MsoNormalTable" border="1" cellspacing="0" cellpadding="0" style="border-width:medium;border-style:none;border-color:initial;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-attachment:initial;background-origin:initial;background-clip:initial;height:778px;width:555px;"><tbody><tr><td width="37" valign="top" style="border-width:1pt;border-style:solid;border-color:windowtext;width:28.1pt;padding:0cm 5.4pt;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong>&#8203;&#8203;<span style="font-size:10pt;font-family:arial, sans-serif;">A</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" valign="top" style="border-top:1pt solid windowtext;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">CÁC ĐƠN VỊ THAM MƯU, TỔNG HỢP</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">1</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/VănPhòngTổngCụcnd.aspx" style="color:green;">Văn phòng Tổng Cục</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">2</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/VụChínhsáchvàPhápchếnd.aspx" style="color:green;">Vụ Chính sách, Pháp chế và Thanh tra</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">3</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/VụHợptácQuốctếvàKhoahọccôngnghệnd.aspx" style="color:green;">Vụ Khoa học, Công nghệ và&nbsp;Hợp tác quốc tế</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">4</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/VụKếhoạchTàichínhnd.aspx" style="color:green;">Vụ Kế hoạch - Tài chính</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">5</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/VụTổchứccánbộnd.aspx" style="color:green;">Vụ Tổ chức cán bộ</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">6</span></strong></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/CụcQuảnlýchấtthảivàCảithiệnMôitrườngnd.aspx" style="color:green;">Vụ Quản lý chất thải</a></span></strong></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">7</span></strong></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/Cụckiểmsoátônhiễmnd.aspx" style="color:green;">Vụ Quản lý chất lượng môi trường</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">8</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/CụcThẩmđịnhvàĐánhgiátácđộngMôitrườngnd.aspx" style="color:green;">Vụ Thẩm định đánh giá tác động môi trường</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">B</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">CÁC ĐƠN VỊ THỰC HIỆN CHỨC NĂNG QUẢN LÝ NHÀ NƯỚC</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">1</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/CụcBảotồnvàĐadạngSinhhọcnd.aspx" style="color:green;">Cục Bảo tồn thiên nhiên và đa dạng sinh học</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">2</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/CUCBVMTmienBac.aspx" style="color:green;">Cục Bảo vệ môi trường miền Bắc</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">3</span></strong></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/Cục-Môi-trường-miền-Trung-và-Tây-Nguyên-nd.aspx" style="color:green;">Cục Bảo vệ môi trường miền Trung và Tây Nguyên</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">4</span></strong></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/Cục-Môi-trường-miền-Nam-nd.aspx" style="color:green;">Cục Bảo vệ môi trường miền Nam&#8203;</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">C</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">CÁC ĐƠN VỊ SỰ NGHIỆP</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">1</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/ViệnKhoahọcQuảnlýMôitrườngnd.aspx" style="color:green;">Viện Khoa học môi trường</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">2</span></strong></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/TrungtâmThôngtinvàDữliệuMôitrườngnd.aspx" style="color:green;">Trung tâm Thông tin và Dữ liệu môi trường</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">3</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/TrungtâmTưvấnvàCôngnghệMôitrường.aspx" style="color:green;">Trung tâm Tư vấn và Công nghệ môi trường</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">4</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/TrungtâmQuantrắcMôitrườngmienBac.aspx" style="color:green;">Trung tâm Quan trắc môi trường miền Bắc</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">5</span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/Trung-tâm-Quan-trắc-môi-trường-miền-Trung-và-Tây-Nguyên.aspx" style="color:green;">Trung tâm Quan trắc môi trường miền Trung và Tây nguyên</a></span></strong><span style="font-size:10pt;font-family:arial, sans-serif;"></span></div></td></tr><tr><td width="37" valign="top" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:28.1pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:1pt solid windowtext;background-color:transparent;"><div style="margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;">6</span></strong></div></td><td width="480" style="border-top:#f0f0f0;border-right:1pt solid windowtext;width:360.05pt;border-bottom:1pt solid windowtext;padding:0cm 5.4pt;border-left:#f0f0f0;background-color:transparent;"><div style="text-align:left;margin:10pt 0cm 6pt;line-height:normal;text-indent:0cm;">
                              <strong><span style="font-size:10pt;font-family:arial, sans-serif;"><a href="/vn/gioithieu/donvitructhuoc/Pages/Trung-tâm-Quan-trắc-môi-trường-miền-Nam.aspx" style="color:green;">Trung tâm Quan trắc môi trường miền Nam</a></span></strong></div></td></tr></tbody></table>&nbsp;</div></div></div>
                  </div>

@endsection